// Local Imports
import { AddShowHandler as AddShowHandlerClass } from './add-show-handler';
import { CheckUserHandler as CheckUserHandlerClass } from './check-user-handler';
import { CreateReviewHandler as CreateReviewHandlerClass } from './create-review-handler';
import { DeleteReviewHandler as DeleteReviewHandlerClass } from './delete-review-handler';
import { EditReviewHandler as EditReviewHandlerClass } from './edit-review-handler';
import { EditUserHandler as EditUserHandlerClass } from './edit-user-handler';
import { FollowHandler as FollowHandlerClass } from './follow-handler';
import { GetCategoryShowsHandler as GetCategoryShowsHandlerClass } from './get-category-shows-handler';
import { GetShowReviewsHandler as GetShowReviewsHandlerClass } from './get-show-reviews-handler';
import { GetUserCategoriesHandler as GetUserCategoriesHandlerClass } from './get-user-categories-handler';
import { GetUserFollowersHandler as GetUserFollowersHandlerClass } from './get-user-followers-handler';
import { GetUserFollowingHandler as GetUserFollowingHandlerClass } from './get-user-following-handler';
import { GetUserHandler as GetUserHandlerClass } from './get-user-handler';
import { GetUserReviewsHandler as GetUserReviewsHandlerClass } from './get-user-reviews-handler';
import { GetUserShowsHandler as GetUserShowsHandlerClass } from './get-user-shows-handler';
import { LoginHandler as LoginHandlerClass } from './login-handler';
import { LogoutHandler as LogoutHandlerClass } from './logout-handler';
import { RegisterHandler as RegisterHandlerClass } from './register-handler';
import { RemoveShowHandler as RemoveShowHandlerClass } from './remove-show-handler';
import { SearchMoviesHandler as SearchMoviesHandlerClass } from './search-movies-handler';
import { SearchTvShowsHandler as SearchTvShowsHandlerClass } from './search-tv-shows-handler';
import { UnfollowHandler as UnfollowHandlerClass } from './unfollow-handler';

// Export instances.
export const AddShowHandler = new AddShowHandlerClass();
export const CheckUserHandler = new CheckUserHandlerClass();
export const CreateReviewHandler = new CreateReviewHandlerClass();
export const DeleteReviewHandler = new DeleteReviewHandlerClass();
export const EditReviewHandler = new EditReviewHandlerClass();
export const EditUserHandler = new EditUserHandlerClass();
export const FollowHandler = new FollowHandlerClass();
export const GetCategoryShowsHandler = new GetCategoryShowsHandlerClass();
export const GetShowReviewsHandler = new GetShowReviewsHandlerClass();
export const GetUserCategoriesHandler = new GetUserCategoriesHandlerClass();
export const GetUserFollowersHandler = new GetUserFollowersHandlerClass();
export const GetUserFollowingHandler = new GetUserFollowingHandlerClass();
export const GetUserHandler = new GetUserHandlerClass();
export const GetUserReviewsHandler = new GetUserReviewsHandlerClass();
export const GetUserShowsHandler = new GetUserShowsHandlerClass();
export const LoginHandler = new LoginHandlerClass();
export const LogoutHandler = new LogoutHandlerClass();
export const RegisterHandler = new RegisterHandlerClass();
export const RemoveShowHandler = new RemoveShowHandlerClass();
export const SearchMoviesHandler = new SearchMoviesHandlerClass();
export const SearchTvShowsHandler = new SearchTvShowsHandlerClass();
export const UnfollowHandler = new UnfollowHandlerClass();
